spring:
  datasource: #配置数据库连接信息
    driver-class-name: com.mysql.cj.jdbc.Driver #驱动类名称
    url: jdbc:mysql://localhost:3306/db04 #数据库连接的url
    username: root #数据库用户名
    password: xingmysql #数据库密码
  servlet:
    multipart:
      max-file-size: 10MB #单个文件上传大小限制
      max-request-size: 1000MB #多个文件

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #指定mybatis输出日志的位置，输出控制台
    map-underscore-to-camel-case: true #驼峰命名与_命名转换

#阿里云OSS配置
aliyun.oss:
  endpoint: https://oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAI5tDEs4kEi5k1T4TRVcF7
  accessKeySecret: Hp4EzlaZQXMCKWSTOJbLerFByXVGMJ
  bucketName: web-it-xing

#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug